config/routes.rb
Satisfaction::Application.routes.draw do
  root :to => "welcome#index"

  get 'login' => 'sessions#new', :as => 'login'
  delete 'logout' => 'sessions#destroy', :as => 'logout'
  get 'signup' => 'users#new', :as => 'signup'

  resources :users, :only => [:new, :create]
  resource :sessions, :only => [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :password, :password_confirmation  

  validates_confirmation_of :password  
  validates_presence_of :password, :on => :create  
  validates_presence_of :username
  validates_uniqueness_of :email, :username
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :username, :password, :remember_me

  def initialize(attributes = nil)
    if attributes.kind_of? Hash
      attributes.each do |attribute, value|
        send "#{attribute}=", value if respond_to? "#{attribute}="
      end
    end
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = UserSession.new
  end

  def create
    @session = UserSession.new params[:user_session]
    @user = login(@session.username, @session.password, @session.remember_me)
    if @user
      redirect_back_or_to root_url, :success => 'Successfully signed in!'
    else
      flash.now.alert = "Incorrect password or username!"
      render :new
    end
  end

  def destroy
    logout
    redirect_back_or_to root_url, :success => 'Successfully signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new  
    @user = User.new  
  end  
    
  def create  
    @user = User.new(params[:user])  
    if @user.save  
      redirect_to root_url, :success => "Signed up!"  
    else  
      render :new  
    end  
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Satisfaction
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      .logo Satisfaction
      %ul.user_menu
        - if current_user
          %li== Hello, #{current_user.username}
          %li= link_to "Sign out", logout_path, :method => :delete
        - else
          %li= link_to "Sign in", login_path
          %li= link_to "Sign up", signup_path
    - flash.each do |name, msg|
      = content_tag :div, msg, :class => "flash #{name}" if msg.is_a?(String)
    #content= yield

app/views/users/new.html.haml
%h1 Sign up

= simple_form_for(@user) do |f|
  = f.error_notification

  .inputs
    = f.input :username
    = f.input :password
    = f.input :password_confirmation

  .actions
    = f.button :submit

app/views/welcome/index.html.haml
%h1 Welcome!